version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    restart: always
    env_file:
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
